### ISSUE TITLE
"You've found a bug!" when clicking on "Dashboard"-Link

### ISSUE THREAD

**Issue by bastian-mer** [Nerivec/zigbee2mqtt-windfront#83]
### Describe the bug

After Updating Zigbee2mqtt to 2.4 and enabling the new frontend everything seems to work fine except the following: I can navigate through the subpages of the frontend, but when i click on "Dashboard" on the top navigation bar, I see the "You've found a bug"-Message.

[state.json.zip](https://github.com/user-attachments/files/20966459/state.json.zip)

 

### To Reproduce

Open frontend, click on "Dashboard" in the top navigation.

### Affected browsers

Firefox

### Stacktrace

```shell
**Current url**: http://192.168.178.9:8080/#/dashboard
**Previous url**: 


**Error type**: TypeError
**Error message**: e[0].toFixed is not a function



Ne@http://192.168.178.9:8080/assets/Feature-Dn8iv4tk.js:1:9577
de@http://192.168.178.9:8080/assets/Feature-Dn8iv4tk.js:1:9791
we<@http://192.168.178.9:8080/assets/Feature-Dn8iv4tk.js:1:10894
uh@http://192.168.178.9:8080/assets/index-vDL8KyrI.js:52:34204
Oh@http://192.168.178.9:8080/assets/index-vDL8KyrI.js:52:62634
BS@http://192.168.178.9:8080/assets/index-vDL8KyrI.js:52:61542
FS@http://192.168.178.9:8080/assets/index-vDL8KyrI.js:52:61090
QS@http://192.168.178.9:8080/assets/index-vDL8KyrI.js:52:75614
wA@http://192.168.178.9:8080/assets/index-vDL8KyrI.js:52:107335
Bz@http://192.168.178.9:8080/assets/index-vDL8KyrI.js:52:106394
Zh@http://192.168.178.9:8080/assets/index-vDL8KyrI.js:52:106222
pA@http://192.168.178.9:8080/assets/index-vDL8KyrI.js:52:103313
kA@http://192.168.178.9:8080/assets/index-vDL8KyrI.js:52:114943
uu@http://192.168.178.9:8080/assets/index-vDL8KyrI.js:52:113513
DA@http://192.168.178.9:8080/assets/index-vDL8KyrI.js:52:113786
XK/Yz/<@http://192.168.178.9:8080/assets/index-vDL8KyrI.js:52:115001
```

**Comment by skvarel** [comment]
See:

https://github.com/Nerivec/zigbee2mqtt-windfront/issues/64
